services:
  hellm_bot:
    build: .
    container_name: HellMBot 
    environment:
      BOT_TOKEN: "insertyourbottokenhere"
      CLIENT_ID: "insertyourclientidhere"
      DB_PATH: "/etc/hellmbot/database.sqlite"
      CIRCLES_COUNT: 9
    volumes:
      - hellm:/etc/hellmbot
    restart: 'unless-stopped'

volumes:
  hellm: