services:
  hellm_bot:
    image: git.orudo.ru/trueold89/hellmbot:latest
    container_name: HellMBot 
    volumes:
      - hellm_db:/etc/hellmbot
    restart: 'unless-stopped'
    environment:
      BOT_TOKEN: "insertyourbottokenhere"
      CLIENT_ID: "insertyourclientidhere"
volumes:
  hellm_db:
